index:
    path:        /
    controller:  Application\Controller\Core
    action:      index

index_2:
    path:
    controller:  Application\Controller\Core
    action:      index

contact:
    path:        /contact
    controller:  Application\Controller\Core
    action:      contact

mailer:
    path:        /mailer
    controller:  Application\Controller\Core
    action:      mailer
